
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ToastContainer } from "./toastify"
import 'react-toastify/dist/ReactToastify.css'
import { Provider } from 'react-redux'
import StoreProvider from './redux/StoreProvider'
// import {Providers} from "../app/redux/Providers"


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Staff Management Portal',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" sizes="16x6" href="/1.png" />
      </head>
      <body className={inter.className}>
        <StoreProvider>
        {children}
        <ToastContainer  position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="colored" />

        </StoreProvider>
      </body>
    </html>
  )
}
